### ISSUE TITLE
build_clusterctl_and_images.yaml playbook points to an inexistent Makefile target

### ISSUE THREAD

**Issue by josecastillolema** [elmiko/cluster-api-kubemark-ansible#1]
https://github.com/elmiko/cluster-api-kubemark-ansible/blob/devel/build_clusterctl_and_images.yaml#L29 points to a Makefile target `docker-capd-build` that does not exist on the [latest cluster-api Makefile version](https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile)

**Comment by elmiko** [comment]
thanks for the issue @josecastillolema , i think i have this fixed on a local copy but i need to push again
